---
users:
  app-000: [mrkn, nishimunea, yonashiro, katsuya, shimizu]
  # A: app-001
  # B: app-002
  # C: app-003
  # D: app-004
  # E: app-005
  # F: app-006
  # G: app-007
  # H: app-008
  # I: app-009
  # J: app-010
  # K: app-011
  # L: app-012
  # M: app-013
  # N: app-014
